""2021-05-13 22:17:04" - ERROR - [json_request_uplink_converter.py] - json_request_uplink_converter - 54 - Cannot find the value from the input data"
""2021-05-13 22:18:42" - ERROR - [json_request_uplink_converter.py] - json_request_uplink_converter - 54 - Cannot find the value from the input data"
""2021-05-13 22:19:40" - ERROR - [json_request_uplink_converter.py] - json_request_uplink_converter - 54 - Cannot find the value from the input data"
""2021-05-13 22:21:31" - ERROR - [json_request_uplink_converter.py] - json_request_uplink_converter - 54 - Cannot find the value from the input data"
""2021-05-13 22:21:36" - ERROR - [json_request_uplink_converter.py] - json_request_uplink_converter - 54 - Cannot find the value from the input data"
""2021-05-13 22:21:41" - ERROR - [json_request_uplink_converter.py] - json_request_uplink_converter - 54 - Cannot find the value from the input data"
""2021-05-13 22:32:28" - ERROR - [json_request_uplink_converter.py] - json_request_uplink_converter - 56 - Cannot find the value from the input data"
""2021-05-13 22:35:45" - ERROR - [json_request_uplink_converter.py] - json_request_uplink_converter - 56 - Cannot find the value from the input data"
""2021-05-13 22:38:10" - ERROR - [json_request_uplink_converter.py] - json_request_uplink_converter - 57 - Cannot find the value from the input data"
""2021-05-13 22:39:24" - ERROR - [json_request_uplink_converter.py] - json_request_uplink_converter - 58 - Cannot find the value from the input data"
